# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files # args: ['--maxkb=123'] (default=500kB).
      # Checks for a common error of placing code before the docstring.
      - id: check-docstring-first
      # Checks that non-binary executables have a proper shebang.
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: check-merge-conflict
      # Add # -*- coding: utf-8 -*- to the top of python files.
      - id: fix-encoding-pragma # args: ["--remove"]
      # Replaces or checks mixed line ending.
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.0.2
    hooks:
      - id: autoflake
        name: Remove unused variables and imports
        entry: autoflake
        language: python
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variables",
            "--expand-star-imports",
            "--ignore-init-module-imports",
          ]
        files: \.py$
  - repo: https://github.com/myint/docformatter
    rev: v1.6.0
    hooks:
      - id: docformatter
        args: ["--in-place", "--wrap-descriptions", "79"]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
