repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.0
    hooks:
      - id: check-added-large-files  # args: ['--maxkb=123'] (default=500kB).
      - id: check-json
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
